version: '2.1'

services:
  angular-cosmosdb:
    image: angular-cosmosdb
    build: .
    environment:
      TWITTER_CALLBACK_URL: http://localhost:3001/api/auth/twitter/callback
    ports:
      - 3001:3001
      - 5858:5858
    expose:
      - 5858
    volumes:
      - .:/usr/src/app
    command: node --inspect src/server/index.js
