version: '2.1'

services:
  angular-cosmosdb:
    image: johnpapa/angular-cosmosdb:latest
    build: .
    environment:
      NODE_ENV: production
    ports:
      - 3001:3001
    command: node index.js
